<a href="https://colab.research.google.com/github/222010328021/222010328021/blob/main/Numpy_Practice_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Welcome to the NumPy practice exercise! Please follow these instructions carefully to complete your assignment:

1. **Read Each Question Carefully**: Each question is designed to test different aspects of your NumPy skills. Make sure to understand what is being asked before you start coding.

2. **Write Your Code in the Provided Cells**: For each question, you will find a corresponding code cell where you should write your solution. Do not modify any other part of the notebook.

3. **Run Your Code**: After writing your code, run the cell to ensure that your solution works as expected. Check the output and make sure it meets the requirements specified in the question.

4. **Complete All Questions**: Make sure you answer all the questions provided. Each question has been included to assess a different skill or concept in NumPy.

5. **Download Your Notebook**: Once you have completed all questions and verified that your solutions are correct, download your notebook file (.ipynb). You can do this by selecting `File > Download > Download .ipynb` from the menu.

6. **Submit Your Work**: Upload the downloaded `.ipynb` file to the designated learning platform for submission.

7. **Check Your Submission**: Ensure that you have submitted the correct file and that it is not corrupted. If there are any issues with the file, you may need to resubmit.

Good luck, and happy coding!

Q1. Import Numpy as `np`

In [ ]:
# write your code here

Q.2 Create a 5x5 array, with numbers ranging from 1-25 and save it in `matrix` variable.
(Use `matrix` variable till question no 10.)

In [ ]:
# write your code here

Q.3 select the subset from `matrix`
```python
array([12,13,14,15],
      [17,18,18,20],
      [22,23,24,25])
```

In [ ]:
# write your code here

Q.4 Select the value 20 from the `matrix`

In [ ]:
# write your code here

Q.5 Select the below subset.(Use `matrix`)
```python
array([[2],
      [7],
      [12]])
```


In [ ]:
# write your code here

Q.6 Select the below subset. (Use `matrix`)
```python
array([21,22,23,24,25])
```

In [ ]:
# write your code here

Q.7 Select the subset below (Use `matrix`)
```python
array([[16,17,18,19,20],
       [21,22,23,24,25]])
```



In [ ]:
# write your code here

Q.8 Get the sum of all the values in `matrix`. (Expected Ans : 325)

In [ ]:
# write your code here

Q.9 Get the standard deviation of the values in `matrix`(Expected Ans : 7.2111025)

In [ ]:
# write your code here

Q. 10 Get the sum of all the columns in `matrix`. (Expected Ans: array([55,60,65,70,75])

In [ ]:
# write your code here

Q.11 Reverse a 1D array.

In [ ]:
# write your code here

Q.12 Find indices of non-zero elements from [10,20,0,0,40,0]

In [ ]:
# write your code here

Q.13 Create a 10x10 array with random values and find the minimum and maximum values.

In [ ]:
# write your code here

Q.14 Create a 10x10 array with 1 on the border and 0 inside.

In [ ]:
# write your code here

Q. 15 Create 8x8 array and fill it with the cheakerboard pattern.

In [ ]:
# write your code here

Q.16 Create a numpy array of size 10 with values ranging from 0 to 1, both excluded.

In [ ]:
# write your code here

Q.17 Create a random array of size 10 and sort it.

In [ ]:
# write your code here

Q.18 Create a random array of size 10 and replace the maximum value with 0.

In [ ]:
# write your code here

Q.19 Create a random array of size 10 and replace the minimum value with 10.

In [ ]:
# write your code here

Q.20 Create an array of size 5x5 and swap two rows.

In [ ]:
 # write your code here

# End!