<a href="https://colab.research.google.com/github/222010328021/222010328021/blob/main/Numpy_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy Assignment

---

**Instructions**

1. **Read Each Question Carefully**: Understand what each question is asking before starting.

2. **Complete the Functions**: For each question, you’ll find a partially completed function in the code cell. Fill in the missing parts to complete the function according to the requirements.

3. **Test Your Function**: After completing each function, run the cell to test if your function works correctly.

4. **Answer All Questions**: Ensure you complete all functions. Each question targets different aspects of NumPy.

5. **Download Your Notebook**: Once you’ve finished and tested all functions, download your notebook file (.ipynb) by selecting `File > Download > Download .ipynb`.

6. **Submit Your Work**: Upload the downloaded `.ipynb` file to the designated platform for submission.

7. **Verify Your Submission**: Check that you have submitted the correct file and that it is not corrupted. Resubmit if necessary.

Good luck, and happy coding!

---

In [1]:
# run this code cell
import numpy as np

**1.Create a function desc which takes an ndarray salaries as argument and prints mean, median, variance and standard deviation of salaries** <br>
- Input  : An ndarray of salaries <br>
- Output : mean , median, variance and standard deviation

In [4]:
# Complete this function
def desc(salaries):
  # write your code here
  mean_salary = np.mean(salaries)
  median_salary = np.median(salaries)
  variance_salary = np.var(salaries)
  std_deviation_salary = np.std(salaries)

  print(f"Mean Salary: {mean_salary}")
  print(f"Median Salary: {median_salary}")
  print(f"Variance of Salaries: {variance_salary}")
  print(f"Standard Deviation of Salaries: {std_deviation_salary}")

salaries_array = np.array([50000, 60000, 75000, 80000, 90000])
desc(salaries_array)

Mean Salary: 71000.0
Median Salary: 75000.0
Variance of Salaries: 204000000.0
Standard Deviation of Salaries: 14282.8568570857


In [5]:
# Execute this code cell (DO NOT MODIFY)

---
---
**2.Create a function quartiles which takes an ndarray salaries as argument and prints first, second and third quartiles** <br>
- Input  : An ndarray of salaries <br>
- Output : q1, q2 and q3

In [6]:
def quartiles(salaries):
  # write your code here
  Q1 = np.percentile(salaries, 25)
  Q2 = np.percentile(salaries, 50)
  Q3 = np.percentile(salaries, 75)

  print(f"First Quartile (Q1): {Q1}")
  print(f"Second Quartile (Q2): {Q2}")
  print(f"Third Quartile (Q3): {Q3}")

In [7]:
salaries = np.array([50000,60000,70000,80000,90000,100000])
quartiles(salaries)

First Quartile (Q1): 62500.0
Second Quartile (Q2): 75000.0
Third Quartile (Q3): 87500.0


---
---
**3.Create a function z_scores which takes an ndarray as argument and returns an ndarray having the z scores of all elements** <br>
- Input  : An ndarray of elements <br>
- Output : An ndarray having z scores

In [8]:
def z_scores(nums):
  # Write your code here
  mean = np.mean(nums)
  std_dev = np.std(nums)
  z_scores = (nums - mean) / std_dev
  return z_scores

In [9]:
nums = np.array([10,20,0,40,50,60])
z_scores(nums)

array([-0.9258201 , -0.46291005, -1.38873015,  0.46291005,  0.9258201 ,
        1.38873015])

---
---
**4.Create a function variance which takes an ndarray of salaries and returns the variance without using the inbuilt variance function.** <br>
 - Input  : An ndarray
 - Output : variance

In [10]:
def variance(salaries):
  # write your code here
  mean_salary = np.mean(salaries)
  N = len(salaries)
  var = np.sum((salaries - mean_salary) ** 2) / N
  return var

In [11]:
salaries = np.array([70000,80000,90000,100000,110000])
variance(salaries)

200000000.0

---
---
**5.Create a function comp_salaries which takes an ndarray of salaries and returns all salaries which are higher than the mean salary.** <br>
 - Input  : An ndarray of salaries
 - Output : an ndarray of salaries higher than the mean

In [12]:
def comp_salaries(salaries):
  # write your code here
  mean_salary = np.mean(salaries)
  higher_salaries = salaries[salaries > mean_salary]
  return higher_salaries

In [13]:
salaries = np.array([76000,69000,40000,58000,85000,92000,94000])
comp_salaries(salaries)

array([76000, 85000, 92000, 94000])

---
---
**6.Create a function cum_sum_diff which takes two ndarrays of same size and returns the difference between cumulative sums at each position.** <br>
- Input  : two ndarrays of having same number of elements
- Output : difference in cumulative sums

In [14]:
def cum_sum_diff(a1, a2):
  # write your code here
  if a1.shape != a2.shape:
        raise ValueError("Both arrays must have the same number of elements.")
  cum_sum1 = np.cumsum(a1)
  cum_sum2 = np.cumsum(a2)

  diff = cum_sum1 - cum_sum2

  return diff

In [15]:
a1 = np.array([10,12,14,8,7,9,20])
a2 = np.array([12,11,8,10,9,13,7])
cum_sum_diff(a1,a2)

array([-2, -1,  5,  3,  1, -3, 10])

---
---
**7.Create two ndarrays a1 and a2 each of shape 4,3 using the randint function having integers between 10 to 50 and concatenate them by axis 0.**

In [16]:
# write your code here
a1 = np.random.randint(10, 51, size=(4, 3))
a2 = np.random.randint(10, 51, size=(4, 3))
concatenated_array = np.concatenate((a1, a2), axis=0)
print("Array a1:")
print(a1)
print("\nArray a2:")
print(a2)
print("\nConcatenated Array:")
print(concatenated_array)

Array a1:
[[24 48 49]
 [22 16 47]
 [31 29 47]
 [16 14 41]]

Array a2:
[[24 11 11]
 [12 32 28]
 [23 48 13]
 [31 50 36]]

Concatenated Array:
[[24 48 49]
 [22 16 47]
 [31 29 47]
 [16 14 41]
 [24 11 11]
 [12 32 28]
 [23 48 13]
 [31 50 36]]


---
---
**8.Create a function compare which takes two ndarrays as arguments having marks of 2 students in 5 subjects each and prints a list having 5 tuples where each tuple contains the max and min marks recived in each subject.**
- Input  : two ndarrays having 5 integers each
- Output : a list with 5 tuples

- sample:
    - input:
        - student 1 : [80,90,70,75,60]
        - student 2 : [75,92,65,90,95]
    - output:
        - [(80, 75), (92, 90), (70, 65), (90, 75), (95, 60)]

In [17]:
def compare(a1, a2):
  # write your code here
  if student1.shape[0] != 5 or student2.shape[0] != 5:
        raise ValueError("Both students must have marks for exactly 5 subjects.")
  result = []

  for i in range(5):
        max_marks = max(student1[i], student2[i])
        min_marks = min(student1[i], student2[i])
        result.append((max_marks, min_marks))

  return result

In [18]:
student1 = np.array([80,90,70,75,60])
student2 = np.array([75,92,65,90,95])
compare(student1, student2)

[(80, 75), (92, 90), (70, 65), (90, 75), (95, 60)]

---
---
**9.Create a function max_min_pos which takes an ndarray as argument and returns the position of maximum element and minimum element from the ndarray.**
- Input  : An ndarray of integers
- Output : A tuple having index of max and min element

In [19]:
def max_min_pos(nums):
  #write your code here
  if not isinstance(nums, np.ndarray):
        raise TypeError("Input must be a NumPy ndarray.")
  pos_max = np.argmax(nums)
  pos_min = np.argmin(nums)
  return (pos_max, pos_min)

In [20]:
nums = np.array([80,10,60,40,90,30,20,50])
max_min_pos(nums)

(4, 1)

---
---
**10.Create a function 'between' that takes an ndarray nums and two integers A and B indicating  a range(B > A). The function should return all elements between A and B present in nums.**
- Input : An ndarray having n elements
- Output : Elements between A and B

In [21]:
def between(nums,A,B):
  #write your code here
  if B <= A:
        raise ValueError("B must be greater than A.")
  result = nums[(nums > A) & (nums < B)]
  return result

In [22]:
nums = np.array([10,40,20,30])
between(nums, 15, 35)

array([20, 30])